language: node_js
node_js:
- "20"
- "22"
branches:
  only:
  - master
  - development
  - /^release\/v.*$/
script:
- npm install -g grunt-cli
- npm install
- cp Gruntfile.default.js Gruntfile.js
- node_modules/.bin/grunt ci
