angular
  .module("orsApp")
  .constant("carBrands", [
    "Abarth",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley",
    "Cadillac",
    "Chevrolet",
    "Citro\u00ebn",
    "Dacia",
    "Ferrari",
    "Fiat",
    "Ford",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lotus",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Morgan Motor",
    "Nissan",
    "Peugeot",
    "Porsche",
    "Renault",
    "Rolls-Royce",
    "Seat",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "VW",
    "Vauxhall",
    "Volvo",
    "\u0160koda"
  ]);
